const charArr = [
    "A-Bomb",
    "Abe Sapien",
    "Abin Sur",
    "Abomination",
    "Abraxas",
    "Absorbing Man",
    "Adam Monroe",
    "Adam Strange",
    "Agent 13",
    "Agent Bob",
    "Agent Zero",
    "Air-Walker",
    "Ajax",
    "Alan Scott",
    "Alex Mercer",
    "Alex Woolsly",
    "Alfred Pennyworth",
    "Alien",
    "Allan Quatermain",
    "Amazo",
    "Ammo",
    "Ando Masahashi",
    "Angel",
    "Animal Man",
    "Annihilus",
    "Ant-Man",
    "Anti-Monitor",
    "Anti-Spawn",
    "Anti-Venom",
    "Apocalypse",
    "Aquaman",
    "Archangel",
    "Arclight",
    "Ares",
    "Astro Boy",
    "Atlas",
    "Atom",
    "Atom Girl",
    "Aurora",
    "Azrael",
    "Aztar",
    "Bane",
    "Banshee",
    "Batgirl",
    "Batman",
    "Beast",
    "Beast Boy",
    "Beetle",
    "Ben 10",
    "Beta Ray Bill",
    "Beyonder",
    "Big Barda",
    "Bird-Man",
    "Bishop",
    "Bizarro",
    "Black Adam",
    "Black Bolt",
    "Black Canary",
    "Black Cat",
    "Black Manta",
    "Black Panther"]