const charArr = [
    "A-Bomb", "Abe Sapien", "Abin Sur", "Abomination",
    "Abraxas", "Absorbing Man", "Adam Monroe", "Adam Strange",
    "Agent 13", "Agent Bob", "Agent Zero", "Air-Walker", "Ajax",
    "Alan Scott", "Alex Mercer", "Alex Woolsly", "Alfred Pennyworth",
    "Alien", "Allan Quatermain", "Amazo", "Ammo", "Ando Masahashi",
    "Angel", "Animal Man", "Annihilus", "Ant-Man", "Anti-Monitor",
    "Anti-Spawn", "Anti-Venom", "Apocalypse", "Aquaman", "Archangel",
    "Arclight", "Ares", "Astro Boy", "Atlas", "Atom", "Atom Girl",
    "Aurora", "Azrael", "Aztar", "Bane", "Banshee", "Batgirl",
    "Batman", "Beast", "Beast Boy", "Beetle", "Ben 10", "Beta Ray Bill",
    "Beyonder", "Big Barda", "Bird-Man", "Bishop", "Bizarro",
    "Black Adam", "Black Bolt", "Black Canary", "Black Cat",
    "Black Manta", "Black Panther", "Black Widow", "Blackout",
    "Blackwing", "Blackwulf", "Blade", "Blink", "Blizzard", "Blob", 
    "Bloodaxe", "Bloodhawk", "Bloodwraith", "Blue Beetle", 
    "Boba Fett", "Bolt", "Bomb Queen", "Boom-Boom", "Booster Gold", 
    "Box", "Brainiac", "Brother Voodoo", "Brundlefly", "Buffy", 
    "Bullseye", "Bumblebee", "Bumbleboy","Bushido", "Cable", "Callisto", 
    "Cameron Hicks", "Cannonball", "Captain America", "Captain Atom", 
    "Captain Britain", "Captain Cold", "Captain Epic", "Captain Hindsight", 
    "Captain Mar-vell", "Captain Marvel", "Captain Planet", "Carnage", "Catwoman",
    "Century", "Chameleon", "Changeling", "Cheetah", "Colossal Boy", "Colossus", "Copycat", "Corsair", "Cottonmouth", "Crimson Crusader", "Crimson Dynamo", "Cyborg", "Cyclops", "Cypher", "Daredevil", "Darkman", "Darkseid","Darth Maul", "Darth Vader", "Dazzler", 
    "Deadman", "Deadpool", "Deadshot", "Deathlok", "Deathstroke", "Diamondback", "Doctor Doom", "Doctor Fate", "Doctor Octopus", "Doctor Strange", "Domino", "Donatello", "Doomsday",
    "Doppelganger", "Dormammu", "Drax the Destroyer", "Electro", "Elektra", "Emma Frost",
    "Enchantress", "Ethan Hunt", "Exodus", "Falcon", "Fin Fang Foom", "Firestar", "Firestorm",
    "Flash", "Flash Gordon", "Franklin Richards", "Franklin Storm","Galactus", "Gambit",
    "Gamora", "General Zod", "Ghost Rider", "Giant-Man", "Gladiator", "Godzilla", "Goku",
    "Goliath", "Greedo", "Green Arrow", "Green Goblin", "Groot", "Hal Jordan", "Han Solo"]